services:
  postgres-payment:
    container_name: postgres-payment
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_DB=paymentdb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d paymentdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:26.3.2
#    ports:
#      - '18080:8080'
#    environment:
#      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
#      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
#    volumes:
#      - ./keycloak:/opt/keycloak/data/import
#    command: start-dev --import-realm --verbose
