services:
  postgres:
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_DB=intershopdb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d intershopdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

networks:
  app-network:
    driver: bridge