-- liquibase formatted sql

-- changeset carbohz:1
CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                           UNIQUE NOT NULL,
    balance     DECIMAL                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
