-- liquibase formatted sql

-- changeset carbohz:1
CREATE TABLE carts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count   BIGINT                                  NOT NULL,
    item_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    image_path  VARCHAR(255)                            NOT NULL,
    price       BIGINT                                  NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id     BIGINT                                  NOT NULL,
    order_id    BIGINT                                  NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    image_path  VARCHAR(255)                            NOT NULL,
    price       BIGINT                                  NOT NULL,
    count       BIGINT                                  NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    balance     DECIMAL                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    total_sum BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);
ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);
ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);