openapi: 3.0.3
info:
  title: Rest API платежей
  version: 1.0.0
paths:
  /balance/{userId}:
    get:
      tags:
        - Payment
      summary: Получение баланса на счёте
      parameters:
        - name: userId
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Баланс на счёте
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: bigdecimal
                required:
                  - balance
        '404':
          description: Пользователь не найден
  /balance:
    post:
      tags:
        - Payment
      summary: Осуществление платежа
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  format: int64
                sum:
                  type: number
                  format: bigdecimal
                  minimum: 0
                  exclusiveMinimum: false
              required:
                - userId
                - sum
      responses:
        '200':
          description: Баланс успешно уменьшен
        '409':
          description: Недостаточно средств