-- liquibase formatted sql

-- changeset carbohz:1
CREATE TABLE carts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count   BIGINT                                  NOT NULL,
    item_id BIGINT,
    CONSTRAINT pk_carts PRIMARY KEY (id)
);

CREATE TABLE items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    image_path  VARCHAR(255)                            NOT NULL,
    price       BIGINT                                  NOT NULL,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    image_path  VARCHAR(255)                            NOT NULL,
    price       BIGINT                                  NOT NULL,
    count       BIGINT                                  NOT NULL,
    order_id    BIGINT,
    CONSTRAINT pk_order_items PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    total_sum BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE orders_items
(
    order_id BIGINT NOT NULL,
    items_id BIGINT NOT NULL
);

ALTER TABLE orders_items
    ADD CONSTRAINT uc_orders_items_items UNIQUE (items_id);

ALTER TABLE carts
    ADD CONSTRAINT FK_CARTS_ON_ITEM FOREIGN KEY (item_id) REFERENCES items (id);

ALTER TABLE order_items
    ADD CONSTRAINT FK_ORDER_ITEMS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE orders_items
    ADD CONSTRAINT fk_ordite_on_item FOREIGN KEY (items_id) REFERENCES items (id);

ALTER TABLE orders_items
    ADD CONSTRAINT fk_ordite_on_order FOREIGN KEY (order_id) REFERENCES orders (id);