-- liquibase formatted sql

-- changeset carbohz:1
CREATE TABLE IF NOT EXISTS item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    image_path  VARCHAR(255),
    count       BIGINT,
    price       INTEGER,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

-- changeset carbohz:2
CREATE TABLE IF NOT EXISTS cart
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cart_items
(
    cart_id BIGINT NOT NULL,
    items_id BIGINT NOT NULL,
    CONSTRAINT fk_cart_items_on_item FOREIGN KEY (items_id) REFERENCES item (id),
    CONSTRAINT fk_cart_items_on_cart FOREIGN KEY (cart_id) REFERENCES cart (id)
);

-- changeset carbohz:3
CREATE TABLE IF NOT EXISTS orders
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders_items
(
    order_id BIGINT NOT NULL,
    items_id BIGINT NOT NULL,
    CONSTRAINT fk_orders_items_on_item FOREIGN KEY (items_id) REFERENCES item (id),
    CONSTRAINT fk_orders_items_on_order FOREIGN KEY (order_id) REFERENCES orders (id)
);