-- liquibase formatted sql

-- changeset carbohz:1
CREATE TABLE IF NOT EXISTS item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    image_path  VARCHAR(255),
    count       BIGINT,
    price       INTEGER,
    CONSTRAINT pk_item PRIMARY KEY (id)
);